### ISSUE TITLE
Seriously.. 

### ISSUE THREAD

**Issue by vvzen** [EdoardoCarlesi/PyRCODIO#1]
I don't want to be a pita, but it doesn't take a genius to realise the name can be considered offensive.
I know it's your own work and you have all the rights to do call it how you want, however, it'd be nice if you tried to be more inclusive and less of a jerk. We should we be all adults here and probably you could only benefit from having a more professional name that doesn't just try to sound like you're one of the cool kids.
Anyway, my 2 cents.

**Comment by EdoardoCarlesi** [comment]
Caro Valerio, che peccato non poter essere tuo amico, chissa' che serate divertenti in tua compagnia mi sto perdendo, a base di inclusiveness, serieta' e maturita'.

E quante lezioni morali avrei potuto apprendere dall'alto del tuo piedistallo !



Che invidia non poter ragionare del tipo:

"Ho trovato su internet una cosa che potrebbe essere offensiva per qualcuno che non conosco! 

Scriviamo subito un messaggio pavoneggiandomi con un inglese sofisticato e con un messaggio passivo/aggressivo ripieno di contenuti tolleranti, cosi' il mondo sara' un posto migliore perche' ho detto a uno sconosciuto che dovrebbe essere piu' inclusivo.

Dannate persone che si fanno delle risate e non pensano che qualcuno ci poteva rimanere offeso!

Invece grazie alla mia mail adesso anche i cattolici potranno usare i repository del dr. Carlesi senza sentirsi offesi o piangere"


Cio' detto:


Ti sei chiesto perche' mai "dovremmo tutti essere adulti"? Perche' , ora fare le battute non e' da adulto? Usare un linguaggio scurrile non e' da adulto? A una certa eta' dovremmo smettere di ridere e usare un linguaggio scurrile?
Chi l'ha detto? Dove sta scritto?



Cosa mai ha fatto un repository di un account con una decina neanche di follower su GitHub - con un nome che non e' neanche una bestemmia tecnicamente - per meritarsi le tue paternalistiche attenzioni?



Perche' mai stai assumendo che potrei solo beneficiare da un nome diverso e "piu' professionale"? 

Chi ti fa pensare che la professionalita' (intesa a modo tuo perche' - spoiler - l'uso di nomi anche volgari e ambigui non e'niente di nuovo in astronomia: https://github.com/astromatic/sextractor tanto per farti un esempio) sia un valore per me?


Non ti sembra arrogante proiettare i tuoi pregiudizi morali e professionali su una persona che non conosci? 



Perche' "it'd be nice" ? Non pensi a tutti i programmatori che si sono fatti una risata vedendo il mio programma? Il buon umore delle altre persone non e' forse un valore?
Essere inclusive non puo' forse valere anche per i programmatori con un po' di senso dell'umorismo? 

Che magari si rompono i coglioni al lavoro e si fanno due risate a vedere un programma con un nome divertente?

I would argue che se cambiassi il nome a questo programma l'unico soggetto a beneficiarne sarebbe il tuo ego.



Comunque, buon divertimento e buona fortuna cercando di rendere internet un posto dove la gente non si puo' offendere e dove sono tutti adulti e rispettosi.



Next time prova a far sparire i video di Germano Mosconi da youtube, che ha seriamente bisogno di diventare un posto piu' inclusive!

**Comment by PsykeDady** [comment]
Amen direi. 😂
Anzi da quasi pastafariano : rAmen

**Comment by vvzen** [comment]
Ciao Edoardo,
ora - io ho scritto 5 righe, tu un po' di più, quindi immagino che il mio presunto "paternalismo" ti abbia toccato in qualche modo. E mi dispiace se suonava paternalistico, non era assolutamente il mio obiettivo.

Ora, come dire, a me frega poco onestamente se tu non cambi nome o se lo lasci tale e quale.
Non t'ho riportato alla censura o segnalato in alcun modo, ho aperto un semplice issue scrivendo che una bestemmia è potenzialmente offensiva - io sono credente e mi sono sentito offeso, ma non è che m'hai scosso nel profondo eh, stai tranquillo. Non ti nascondo che è anche fastidioso il fatto che tu abbia subito pensato ai cattolici - come se fossero gli unici infastiditi che credono in Dio.

Ho scritto **2 cents** per dirti che è come la penso io, nel 2020.
E ho scritto inglese perché in questo modo è comprensibile a più persone. Sofisticato non me pare proprio perché PITA non è proprio sofisticatissimo.

Comunque, non ho voglia di entrare in sofismi su internet, tanto è difficile capirsi e lo rimarrà sempre - credo abbiamo valori diversi e sta bene così, ognuno si porta appresso la sua cultura. "Adulto" per me vuol dire che accetti che qualcun altro possa non condividere quello che per te fa ridere e magari lo metti in discussione. Per dirti, `Sextractor` per esempio non è offensivo assolutamente, almeno non ai miei occhi.

In un mondo che si domanda che forse è il momento di cambiare il nome del branch `master` in qualcos'altro che non rimandi alla cultura dello schiavismo, pensavo che non fosse chiedere troppo avere il nome di una repo che non richiami a una bestemmia.
Se a te fa ridere, ci sta tutta, a me non fa ridere e mi richiama a un tipo di cultura che non condivido.
È per il mio ego? Certo, è per le persone che condividono la mia stessa cultura e la stessa visione dell'open source.
Alla fine anche tu lo fai per far ridere quelli che la pensano come te. Insomma, a ognuno il suo, appunto.
Per farti un esempio però: se faccio una repo e la chiamo `NEGRO - Neural Experiments on Generic Robotic Operations` fa ride pure ma qualcuno si potrebbe offendere - credo sia lo stesso meccanismo.

Detto ciò, ti chiedo scusa per le mie 4 righe - non volevo offenderti, né moralizzarti, né proporre di togliere Germano Mosconi da YouTube, né censurare o altro. Speravo in confronto pacifico e che non andasse sul personale (come hai provato a metterla tu) - ma mi rendo conto che non è possibile, e va bene così. Non è questione di stare alla cattedra o meno ma di essere aperti all'altro, d'altronde se hai fatto una repo open source immagino che ti interessi che qualcuno contribuisca in qualche modo. Questo era il mio contributo.

Mi spiace che chiedere una cosa col il tono in cui l'ho chiesta appaia come essere arrogante.
Mi scuso se è sembrato che fosse così.

**Comment by vvzen** [comment]
PS: nonostante io non trovi Sextractor offensivo, c'è comunque chi ha avuto da ridire: https://github.com/astromatic/sextractor/issues/8 
Nello specifico ti rimando al commento di `jradavenport` nell'issue che ti ho linkato, che probabilmente espone quello che voglio dire molto meglio di come potrei mai farlo io.
Tra l'altro, alla fine la repo è evoluta in https://github.com/astrorama/SourceXtractorPlusPlus

**Comment by EdoardoCarlesi** [comment]
Allora,


Di base ci sono poche cose che mi urtano come il moralismo PC che va tanto di moda questi giorni per fare virtue signaling inutile. Per questo mi sono dilungato nella risposta.



Poi deciditi: nella prima mail non hai fatto nessun riferimento al tuo essere credente (anzi hai detto might offend someone), poi hai scritto rAmen (sono pastafariano) ed ora sei improvvisamente diventato credente. Un malpensante potrebbe pensare che sei un po' paraculo e cerchi di buttarci il discorso dell'offesa personale in corso d'opera, ma lasciamolo pensare ai malpensanti. 



Ho pensato ai cattolici per una semplice ragione: la bestemma e' un fatto puramente italiano, e gli italiani credenti sono prevalentemente cattolici. E - news flash - a moltissimi non frega un cazzo che qualcuno chiami un programma PyRCODIO.

Comunque, la prossima volta cerchero' di essere inclusive anche quando penso a chi si offende.



Riguardo all'open source: non so se ti rendi conto che siamo in 3 o 4 in tutto il mondo ad analizzare simulazioni cosmologiche del gruppo locale di galassie, che e' il tipo di analisi a cui PyRCODIO e' dedicato. Il codice e' aperto piu' per ragioni di peer-review e trasparenza del processo scienfico, cosi' che un referee che mi controlla il paper ha accesso al codice usato per l'analisi. Gli altri 3 ricercatori/ricercatrici/ricercat* che si occupano di near field cosmology hanno i loro codicini scritti per le loro esigenze e non mi aspetto che usino il mio, e' piu' probabile che tu scopra il vaccino per il COVID piuttosto.



Noto che hai cambiato anche la definizione di 'adulto' adesso. Prima era riferito al fatto che usavo un linguaggio scurrile, ora adulto vuol dire accettare le critiche.
A me va benissimo che a te non piaccia il mio umorismo, ma ti spoilerero' una cosa: nel 2020 non sei obbligato a soffermarti su qualsiasi cazzata che trovi su internet e lamentarti, puoi cambiare pagina e far finta di niente, e preservare indignazione ed energie per cose serie. Anche questo e' essere adulto. 

Se dovessi mandare una mail a tutti quelli che non mi fanno ridere o mi urtano i nervi avrei smesso di lavorare da tempo.



Se vuoi equiparare razzismo e bestemmie fai pure. A me se qualcuno si offende o meno frega molto relativamente, ed e' giusto cosi': l'offesa in molti casi e' un discorso puramente soggettivo e non ha senso avallarla a prescindere. Il pubblico spazio e' fatto anche per permettere a tutti di esprimersi in maniera che a volte risulta offensiva per gli altri, perche' la liberta' di espressione non puo' essere limitata dal soggettivo senso di "mi sento offeso da X, togliete X dalla mia vista". Soprattutto se si parla di un repo con 20 iscritti.



Ma poi, pensa a tutti quelli che si offendono perche' vedono coppie gay mano nella mano, o perche' vedono nelle loro citta' degli immigrati, o perche' vedono gente che gira con simboli religiosi non cristiani o come succede altre volte, perche' sente gente parlare in lingue che non capisce. 

Dobbiamo dargli ragione? Si sono offesi! Non essere gay/nero/musulmano, potresti offendere qualcuno! Non parlare arabo, senno' qualcuno potrebbe offendersi!


Oppure l'offesa vale solo quando viola certi canoni (rigorosamente PC), mentre se altre persone si offendono vale dimeno? 

E chi li decide questi canoni? Tu? la Meloni? Il consiglio dei saggi? la task force di Conte? 







Riguardo a SEXtractor offensivo o non offensivo: e' irrilevante se qualcuno si offende o meno, il punto era solo farti presente che nomi fantasiosi e volgari si usano nella nostra comunita'. A me personalmente SEXtractor sembra un nome di cattivo gusto ma non sono cazzi miei e che ciascuno faccia un po' il cazzo che gli pare, non sono obbigato a clonarmi il loro repo.





Buona fortuna a rendere internet un posto senza offese per nessuno!

**Comment by PsykeDady** [comment]
@EdoardoCarlesi  rAmen l' ho scritto io in risposta a te per esprimere il mio assenso alla tua risposta 

scusa per averti confuso 😂 effettivamente non era necessario

**Comment by vvzen** [comment]
Guarda fa niente dai.
Il fatto che entri sempre sul personale e il tuo tono aggressivo indica quanto ti interessa davvero quello che dico o quanto invece ti interessa solo di attaccarmi sul piano retorico.
Pensala come vuoi - non sarò io a convincerti che l'inclusione, la tolleranza e l'apertura verso ogni forma di religione, minoranza sociale, bla bla bla.. non sono solo cazzate da progressisti finti o una questione di "moda" ma problemi seri che la cultura dominante (di cui faccio parte anche io, uomo, bianco, europeo, con passato da colonizzatore etc..) deve porsi.
Secondo te è solo virtue signaling inutile ? Bene, non ti fermerò dal pensarlo.
Ah - gli esempi che mi hai riportato sono inutili in quanto riportano una condizione, non un'azione. Non mi posso offende che sei ateo, mi posso offende che mi imbratti casa con una scritta o insulti me e i miei valori. Ma ho capito che a te poco frega quindi la taglio corta qui, proseguire è inutile e sta facendo perdere tempo a entrambi.
Buona cosmologia e buono sviluppo.

**Comment by EdoardoCarlesi** [comment]
Non ce la faccio proprio ma ste minchiate PC da salotto bene di gente con la maglia del Che mi fanno proprio uscire di testa...


Ma ti sei chiesto perche' mai dovrei avere interesse a scambiare idee con te? Pensi davvero di essere una persona cosi' profonda e interessante, che propone riflessioni stimolanti?


Non ti sembra arrogante pensare di avere qualcosa ti tanto importante da dover comunicare (anzi, delle lezioni morali da dover impartire) da dover molestare uno sconosciuto perche' ti senti talmente imbevuto di spirito di giustizia suprema da dover far capire che il mondo dev'essere piu' tollerante (secondo i tuoi supremi standard PC, che non prevedono ironia che possa offendere qualcuno perche' siamo nel 2020 e dobbiamo annoiarci nel rispetto reciproco).



Ma che ti ho chiesto di venirti a spizzare il mio repository? Sono venuto a imbrattarti casa?
Ti ripeto, se vuoi andare in giro a ripulire internet dalle cose che potrebbero offendere qualcuno, buona fortuna. 



Ma poi che ne sai tu di apertura e tolleranza? Ma non ti senti un tantino arrogante a doverti mettere su un piedistallo a dare lezioncine morali a qualcuno che non conosci sulla base del nome di un repo? 



Eccola la... uomo bianco europeo con passato da colonizzatore. Tu chi hai colonizzato di grazia? 

Tuo nonno forse, o il tuo bisnonno contadino al massimo sara' stato mandato in Libia (11-45) o in Etiopia (36-41) a prendersi delle mazzate dagli inglesi, come il mio e come tutti i poveri italiani mandati a farsi massacrare in Africa dal governo di turno. Che vantaggio ne ha tratto? Spoiler: nessuno! ne' lui, ne' il paese che l'ha mandato a farsi legnare!



Cultura dominante per te, probabilmente, che guardi il mondo da una prospettiva EU-centrica (incl. UK). Con me caschi male purtroppo. Mi sono fatto settimane di volontariato coi rifugiati siriani nei balcani (durante le crisi 2015 e 2016 con Refugee Aid Serbia, siccome parlo fluentemente Arabo e Serbocroato), ho vissuto tre anni a Gerusalemme, ho girato la meta' dei campi rifugiati palestinesi, ho insegnato tedesco ai siriani a Berlino, parlo una decina di lingue fluentemente e sono anni che ho imparato a guardare il mondo da prospettive tutt'altro che anglo-centriche.

 

Se avessi orgini serbe e quindi con un passato di colonizzato dal 1389 al 1878 dall'Impero Ottomano, si applicherebbe lo stesso discorso di "uomo bianco europeo" ? 

O se fossi un bosniaco musulmano, bianco, europeo? Se fossi un bianco caucasico russo con alle spalle centinaia di anni di oppressione prima zarista poi sovietica?
C'entrerebbe qualcosa l'essere bianco ed europeo? Vuoi che vada avanti a farti esempi di popoli bianchi ed europei che non hanno nessun passato di privilegio e colonialismo? I Finlandesi chi hanno mai colonizzato di grazia? 

Che sono stati centinaia di anni sotto Svedesi, poi Russi, poi invasi dall'URSS ripetute volte alla fine degli anni 30 e durante WWII con pezzi di Karelia strappati dall'armata rossa? Eppure sono bianchissimi ed europeissimi.



Perche' non ti interroghi sul fatto che appena parli di europei e bianchi ti riferisci solo ad un piccolo sottoinsieme dei popoli europei e bianchi?

Non di certo gli slavi del sud, gli albanesi, i georgiani, gli armeni, i russi al di qua degli Urali, i polacchi, i rumeni o i qualcuno dei popoli baltici.



Sai quanti arabi bianchi e ricchi ci sono in giro per il medioriente?

Sai cosa pensano i cinesi di queste minchiate PC? Ci hanno coniato un termine apposta: Baizuo. 

O cosa ne pensano serbi, palestinesi, russi o polacchi di questa mentalita' perbenista?


Ecco, io la penso come loro.


Buon tutto

**Comment by gionniboy** [comment]
Sono deluso: neanche un bestemmione in questo thread.

Mi sento molto molto escluso. Per favore non escludetemi: buttate qualche porco mentre discutete.

**Comment by ps1dr3x** [comment]
Ma vai a cagare @vvzen PyRCODIO

**Comment by taifu** [comment]
Followo subito il progetto perché la risposta di @EdoardoCarlesi è da standing ovation.

**Comment by nocturn9x** [comment]
Sembra quasi più una stronzata del cambiamento master->main..., io mi sento offeso da questo issue, come la mettiamo? :D

**Comment by stecb** [comment]
@EdoardoCarlesi 👏 👏 👏 👏 👏  NUMERO 1!

**Comment by ae-mo** [comment]
Adoro tutto ciò e commento per non perdermi neanche una goccia di ignoranza

**Comment by cesare-montresor** [comment]
@vvzen  E se fossi tu a discriminare la sua forma di preghiera? Stando al tuo CTO pare che sia tutto ok.
https://www.ilgiornale.it/news/cronache/papa-francesco-anche-arrabbiarsi-dio-pregare-1355184.html

**Comment by stecb** [comment]
> @vvzen E se fossi tu a discriminare la sua forma di preghiera? **Stando al tuo CTO** pare che sia tutto ok.
> https://www.ilgiornale.it/news/cronache/papa-francesco-anche-arrabbiarsi-dio-pregare-1355184.html

Quel "Stando al tuo CTO" mi ha fatto rotolare @cesare-montresor 😂

**Comment by MRtecno98** [comment]
> I don't want to be a pita, but it doesn't take a genius to realise the name can be considered offensive.
> I know it's your own work and you have all the rights to do call it how you want, however, it'd be nice if you tried to be more inclusive and less of a jerk. We should we be all adults here and probably you could only benefit from having a more professional name that doesn't just try to sound like you're one of the cool kids.
> Anyway, my 2 cents.

Bruh

**Comment by smlb** [comment]
> 
> 
> Sono deluso: neanche un bestemmione in questo thread.
> 
> Mi sento molto molto escluso. Per favore non escludetemi: buttate qualche porco mentre discutete.

https://youtu.be/1SUPD0zT9oA?t=164

**Comment by emilianomaccaferri** [comment]
da un lato: hahaha che ridere ignoranza bomber le bestemmie che ridere hahaha ho trent'anni e mi fan ridere le bestemmie woooo bomber bomber bomberone 

dall'altro lato: REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE IL PROGETTO È TUO MA IO VOGLIO CHE TU CAMBI IL NOME PERCHÉOUOSANDIUH ASUIYBASIUYDBASUYDB AUSD

0-0 palla al centro

**Comment by taifu** [comment]
Col cazzo 0-0.

100 a 0 per Edoardo.

**Comment by emilianomaccaferri** [comment]
> Col cazzo 0-0. 100 a 0 per Edoardo.
> […](#)
> On Tue, 20 Oct 2020 at 12:03, Emiliano Maccaferri ***@***.***> wrote: 0-0 palla al centro

ok king

**Comment by EdoardoCarlesi** [comment]
@emilianomaccaferri certo, mi sono proprio posto cosi' come descrivi tu nel rispondere!

Per fortuna che sei super partes e con la tua maturita' al di sopra di tutti noi riesci a giudicare la situazione in maniera imparziale e saggia. 

Andare in giro per l'internet a propagandare giustizia sociale, buone maniere e moralismo e chiedere di essere lasciato in pace di esprimersi nei propri spazi sono due comportamenti assolutamente simmetrici ed equiparabili, 0-0, giustissimo !

**Comment by veggero** [comment]
Dopo aver letto la conversazione posso solo dire: Edoardo, che peccato non poter essere tuo amico, chissa' che serate divertenti in tua compagnia mi sto perdendo.

**Comment by EdoardoCarlesi** [comment]
> Dopo aver letto la conversazione posso solo dire: Edoardo, che peccato non poter essere tuo amico, chissa' che serate divertenti in tua compagnia mi sto perdendo.

Puoi sempre diventare mio fan e passare serate (a pagamento) tipo questa in mia compagnia: 
https://youtu.be/iu4A8kcw1_g

appena finisce il COVID e posso riprendere a suonare

**Comment by PsykeDady** [comment]
@veggero vai ad ascoltare i CD nei nanowars che 4 risate con lui te le fai lo stesso :joy: sono epici

**Comment by stecb** [comment]
> > Dopo aver letto la conversazione posso solo dire: Edoardo, che peccato non poter essere tuo amico, chissa' che serate divertenti in tua compagnia mi sto perdendo.
> 
> Puoi sempre diventare mio fan e passare serate (a pagamento) tipo questa in mia compagnia:
> https://youtu.be/iu4A8kcw1_g
> 
> appena finisce il COVID e posso riprendere a suonare

Spettacolo! non vedo l'ora ritorniate (e ritornino tutti in realta') a suonare live <3

**Comment by emilianomaccaferri** [comment]
> @emilianomaccaferri certo, mi sono proprio posto cosi' come descrivi tu nel rispondere!
> 
> Per fortuna che sei super partes e con la tua maturita' al di sopra di tutti noi riesci a giudicare la situazione in maniera imparziale e saggia.
> 
> Andare in giro per l'internet a propagandare giustizia sociale, buone maniere e moralismo e chiedere di essere lasciato in pace di esprimersi nei propri spazi sono due comportamenti assolutamente simmetrici ed equiparabili, 0-0, giustissimo !

dai, era uno scherzo... non si può proprio dire niente su internet eh??????? mamma mia che moralista :(

non sto prendendo le parti di nessuno, anzi, con un po' di ironia :))))) (visto che a voi piace tanto) sto descrivendo la situazione. purtroppo ora stai reagendo come la persona che si è presa su e ha aperto un issue per il nome della repo. diciamo che vi dà fastidio un determinato tipo di roba a voi su internet che va "di moda" criticare e siete tutti pronti a prendere le difese dei vostri amiconi del web con dei discorsi fuorvianti.

la prossima volta, quando darai il prossimo nome divertentissimo alla tua repo (ti consiglio un qualcosa di originale tipo PyOCANE), visto che è il tuo profilo e puoi farci quello che vuoi (tue parole), ti suggerisco di passare oltre un issue del genere, perché sebbene la persona che l'ha aperto poteva benissimo sorvolare, tu potevi, visto che siamo tutti dei buonisti che vengono offesi da tutto, benissimo rispondere in un altro modo e chiudere definitivamente l'issue, al posto che confermare la mia tesi del bomberone, facendo delle scenate che non si addicono a nessuno e scrivendo robe che non c'entrano niente con l'issue in primo luogo e scendendo sotto il livello delle persone che tu reputi "troppo moraliste per stare su internet". alla fine sei uno che, a differenza di quanto dice, non sa scherzare e prende tutto sul serio e quindi non dovrebbe stare su internet a sua volta (a detta tua).

my two cents

**Comment by emilianomaccaferri** [comment]
detto questo: signing off, ho visto sta roba su ignuranza e sinceramente potevo sorvolare anche io

**Comment by EdoardoCarlesi** [comment]
@emilianomaccaferri ci mancheranno i tuoi imprescindibili contributi ma soprattutto ci manchera' la tua punteggiatura ineccepibile!

**Comment by emilianomaccaferri** [comment]
> @emilianomaccaferri ci mancheranno i tuoi imprescindibili contributi ma soprattutto ci manchera' la tua punteggiatura ineccepibile!

vai tranquillo king, tutti sbagliano alla fine.
basta solo ammetterlo

**Comment by gbonfiglio** [comment]
Non vi dico come ci si sente ad aver letto tutta la issue rendendosi conto solo alla fine che @EdoardoCarlesi è il bassista dei Nanowar of Steel.

**Comment by tapionx** [comment]
Alla pugna 🤙

**Comment by blasco991** [comment]
mi avete rallegrato per un intero anno con questo flame 😄 #cheapeu

**Comment by vihai** [comment]
LOL, quanta epicità in questo thread.

Aspettati di venir segnalato alla PC police. Vedrai che succederà... eccome se succederà...

Nel caso ti offro un account sul mio repository GitLab self-hosted e PC-unfriendly.

Ora scappo che devo rinominare blacklist in blocklist stare attento nei miei manuali a parlare solo di plug e socket perché connettori maschi e femmine sono discriminanti.

**Comment by gionniboy** [comment]
> Non vi dico come ci si sente ad aver letto tutta la issue rendendosi conto solo alla fine che @EdoardoCarlesi è il bassista dei Nanowar of Steel.

vabbe lo sappiamo che sei sempre "in ritardo" tu  gioggio

**Comment by DavGatto** [comment]
Vorrei usare il programma, ma non so niente di astronomia e quindi non posso usarlo, PyRCODIO.

**Comment by dankydev** [comment]
Github è un posto meraviglioso

**Comment by pirods** [comment]
Che mezz'ora ben spesa. @EdoardoCarlesi non vedo l'ora di poter assistere nuovamente a serate (a pagamento, sia ben inteso) in tua compagnia.

**Comment by ae-mo** [comment]
@pirods #qualitycontent

**Comment by AleMScof** [comment]
Chi è qui grazie all'algoritmo di Youtube?
cit.

**Comment by ciacco85** [comment]
> Non vi dico come ci si sente ad aver letto tutta la issue rendendosi conto solo alla fine che @EdoardoCarlesi è il bassista dei Nanowar of Steel.

Ma che da vero?? @EdoardoCarlesi  ho un nuovo idolo!

**Comment by kidpixo** [comment]
@EdoardoCarlesi ho scoperto questa issue dopo qualche anno, ma veramente devo fare standing ovation.

Sono molto d'accordo col tuo modo di vedere la cosa.

Eurocentrismo e buonismo spicciolo sono cose non belle (ad essere buoni) e quasi sempre non percepite da chi parla.
A onor del vero anche fior fiore di antropologi hanno fatto gli stessi errori.

Mi inchino alle tue esperienze passate: aiuto degli altri , conoscenza della lingue (sto provando col giapponese dopo qualche altra piano piano ed é difficile) etc.

Sono un astrofisico e capisco anche la questione "piccola comunitá".

Che dire, ti apprezzo.
